[project]
name = "docxtpl"
dynamic = ["version"]
description = "Python docx template engine"
authors = [{name="Eric Lapouyade", email="elapouya@proton.me"}]
readme = "README.rst"
license = {text="LGPL-2.1-only"}
requires-python = ">=3.7"
classifiers=[
    "Intended Audience :: Developers",
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
keywords = ["jinja2"]
dependencies = [
    "python-docx",
    "jinja2",
    "lxml",
]

[project.optional-dependencies]
subdoc = ["docxcompose"]
docs = ["Sphinx", "sphinxcontrib-napoleon"]

[dependency-groups]
dev = [
    "sphinx-book-theme",
    "ruff; python_version >= '3.9'",
    "twine; python_version >= '3.9'",
    "mypy >=1.17.0; python_version >= '3.9'",
    "lxml-stubs >=0.5.1; python_version >= '3.9'",
]

[project.urls]
homepage = "https://github.com/elapouya/python-docx-template"
repository = "https://github.com/elapouya/python-docx-template.git"
document = "https://docxtpl.readthedocs.org"

[tool.pdm]
version = {source="file", path="src/docxtpl/__init__.py"}

[tool.poetry]
version = '0.0.0'

[tool.poetry-plugin-version]
source = "src/docxtpl/__init__.py"

[tool.mypy]
pretty = true
python_version = "3.9"
check_untyped_defs = true
warn_unused_ignores = true
exclude = ["docs", "build", "setup.py"]

[[tool.mypy.overrides]]
module = ["docxcompose.*"]
ignore_missing_imports = true

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.ruff]
line-length = 127

[tool.ruff.lint]
extend-select = [
    "I",      # https://docs.astral.sh/ruff/rules/#isort-i
]

[tool.pdm.scripts]
tree = "pdm list --tree"
style = {composite = ["ruff format", "ruff check --fix {args}"]}
typehints = {composite = ["mypy .", "uv build", "twine check dist/*"]}
check = {composite = ["ruff format --check", "ruff check", "typehints"]}
lint = {composite = ["style", "typehints"]}
test = "python tests/runtests.py"
ci = {composite = ["check", "test"]}
